general.import = ["~/.config/alacritty/keybindings.toml"]
[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
opacity = 0.7
decorations = "full"
padding = { x = 5, y = 5 }

[font]
size = 11.0

[font.normal]
  #family = "Terminus"
  # family = "Fira code"
 #family = "ProggyVector"
family = "VictorMonoNerdFont"
  # family = "Dina"
  # family = "Terminus"
  style = "Regular"


[scrolling]
history = 10000

[selection]
save_to_clipboard = true


[mouse]
hide_when_typing = true


[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.3

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Beam"


 # Cursor style
  #
  #Values for `style`:
  #   - â–‡ Block
  #   - _ Underline
  #   - | Beam


# [[keyboard.bindings]]
# key = "V"
# mods = "Control|Shift"
# action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Control|Shift"
# action = "Copy"

# [[keyboard.bindings]]
# key = "Insert"
# mods = "Shift"
# action = "PasteSelection"

# [[keyboard.bindings]]
# key = "Key0"
# mods = "Control"
# action = "ResetFontSize"

# [[keyboard.bindings]]
# key = "Equals"
# mods = "Control"
# action = "IncreaseFontSize"

# [[keyboard.bindings]]
# key = "Plus"
# mods = "Control"
# action = "IncreaseFontSize"

# [[keyboard.bindings]]
# key = "Minus"
# mods = "Control"
# action = "DecreaseFontSize"

# [[keyboard.bindings]]
# key = "F11"
# mods = "None"
# action = "ToggleFullscreen"

# [[keyboard.bindings]]
# key = "Paste"
# mods = "None"
# action = "Paste"

# [[keyboard.bindings]]
# key = "Copy"
# mods = "None"
# action = "Copy"

# [[keyboard.bindings]]
# key = "L"
# mods = "Control"
# action = "ClearLogNotice"

# [[keyboard.bindings]]
# key = "L"
# mods = "Control"
# chars = "\f"

# [[keyboard.bindings]]
# key = "PageUp"
# mods = "None"
# action = "ScrollPageUp"
# mode = "~Alt"

# [[keyboard.bindings]]
# key = "PageDown"
# mods = "None"
# action = "ScrollPageDown"
# mode = "~Alt"

# [[keyboard.bindings]]
# key = "Home"
# mods = "Shift"
# action = "ScrollToTop"
# mode = "~Alt"

# [[keyboard.bindings]]
# key = "End"
# mods = "Shift"
# action = "ScrollToBottom"
# mode = "~Alt"

